# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: true
check_commit_message: true
check_manifest: true
check_stray_pulpcore_imports: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: true
docs_test: true
plugin_app_label: deb
plugin_camel: PulpDeb
plugin_camel_short: Deb
plugin_caps: PULP_DEB
plugin_caps_short: DEB
plugin_dash: pulp-deb
plugin_dash_short: deb
plugin_name: pulp_deb
plugin_snake: pulp_deb
publish_docs_to_pulpprojectdotorg: true
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: aa499d7938ed
pydocstyle: true
pypi_username: pulp
redmine_project: pulp_deb
test_bindings: false
test_cli: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: true
test_s3: true
update_redmine: true

